### ISSUE TITLE
Circular data structure not dumped correctly

### ISSUE THREAD

**Issue by perlancar** [Cside/Data-Dumper-OneLine#1]
% perl -MData::Dumper::OneLine -E'$a={b=>1}; $a->{a}=$a; say Dumper $a'
{a => $VAR1, b => 1}

Compare with:
% perl -MData::Dump::OneLine=dump1 -E'$a={b=>1}; $a->{a}=$a; dump1 $a'
do { my $a = {a => 'fix', b => 1}; $a->{a} = $a; $a; }

**Comment by Cside** [comment]
This is a specification of Data::Dumper. D::D::OneLine inherrits Data::Dumper.

**Comment by perlancar** [comment]
Just a comment: in Data::Dumper, circular references are dumped using a series of statements, by setting $Data::Dumper::Purity = 1. So this does not need any change in Data::Dumper::OneLine.
